spring:
  application:
    name: builder-service

  rabbitmq:
    host: localhost
    port: 5672

  cloud:
    function:
      definition: builderOrderAndNotify
    stream:
      bindings:
        builderOrderAndNotify-out-0:
          group: orders
          destination: notifyOrders
        builderOrderAndNotify-in-0:
          group: orders
          destination: builderOrders
#server:
#  port: 9092

management:
  health:
    defaults:
      enabled: true
    binders:
      enabled: true
    cassandra:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
