spring:
  application:
    name: builder-service

  kafka:
    bootstrap-servers: localhost:9093

  cloud:
    stream:
      function:
        definition: builderOrderAndNotify
      bindings:
        builderOrderAndNotify-out-0:
          group: orders
          destination: notifyOrders
        builderOrderAndNotify-in-0:
          group: orders
          destination: builderOrders
#server:
#  port: 9092

management:
  health:
    defaults:
      enabled: true
    binders:
      enabled: true
    cassandra:
      enabled: false
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
