apiVersion: v2
appVersion: v2.1.0
description: 'Loki: like Prometheus, but for logs.'
home: https://grafana.com/loki
icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
kubeVersion: ^1.10.0-0
maintainers:
- email: lokiproject@googlegroups.com
  name: Loki Maintainers
name: loki-stack
sources:
- https://github.com/grafana/loki
version: 2.4.0
dependencies:
  - name: "loki"
    condition: loki.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^2.5.0"
  - name: "promtail"
    condition: promtail.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^3.5.0"
  - name: "fluent-bit"
    condition: fluent-bit.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "^2.2.0"
  - name: "grafana"
    condition: grafana.enabled
    version: "~6.8.2"
    repository:  "https://grafana.github.io/helm-charts"
  - name: "prometheus"
    condition: prometheus.enabled
    version: "~13.8.0"
    repository:  "https://prometheus-community.github.io/helm-charts"
  - name: "filebeat"
    condition: filebeat.enabled
    version: "~7.12.1"
    repository:  "https://helm.elastic.co"
  - name: "logstash"
    condition: logstash.enabled
    version: "~7.12.1"
    repository:  "https://helm.elastic.co"

