grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: "http://localhost:3000/grafana"
      serve_from_sub_path: true
  ingress:
    enabled: false
    # TODO https://github.com/grafana/helm-charts/tree/main/charts/grafana
    annotations:
      kubernetes.io/ingress.class: "ambassador"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    path: /grafana/?(.*)
    pathType: "Prefix"
    hosts:
      - localhost
prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
loki:
  persistence:
    enabled: false
    storageClassName: "standard"
    size: "5Gi"
promtail:
  config:
    lokiAddress: "http://loki:3100/loki/api/v1/push"
