spring:
  application:
    name: order-service
  data:
    cassandra:
      schema-action: create_if_not_exists
      request:
        timeout: 5s
      local-datacenter: datacenter1
      keyspace-name: opentelemetry
  webflux:
    base-path: /order

  kafka:
    bootstrap-servers: localhost:9093

  cloud:
    stream:
      function:
        definition: builderOrders
      bindings:
        builderOrders-out-0:
          group: orders
          destination: builderOrders

management:
  health:
    defaults:
      enabled: true
    binders:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
